### ISSUE TITLE
there's a Swift 5 migration on the Horizon?

### ISSUE THREAD

**Issue by jplazcano87** [airsidemobile/JOSESwift#166]
Using the Swift 5 migration and there's a lot of deprecated method calls, there's any plans of update this calls and perform a Swift 5 migration

**Comment by daniel-mohemian** [comment]
Hi @jplazcano87 👋 

Thanks for reporting this. While we already migrated the source code to Swift 5 in #154, it turned out we did not update the Swift version in the podspec. 🤕 

I've done that in #167. Once this is merged and released, you should not get the migration prompt anymore.

As for the deprecated method calls, what exactly are you seeing there? I could not reproduce that using a fresh install of version 1.8.1 in a Swift 5 project.

**Comment by jplazcano87** [comment]
Thanks for the quick reply, i'm getting all this deprecation messages all over the place
<img width="1029" alt="Captura de Pantalla 2019-08-01 a la(s) 08 30 15" src="https://user-images.githubusercontent.com/3168897/62293459-ac180600-b436-11e9-82a4-3dcecd1fde53.png">

**Comment by daniel-mohemian** [comment]
These warnings were fixed in version 1.8.1 (via #154). Which version of JOSESwift are you using?

**Comment by jplazcano87** [comment]
it was a problem with the version, now the warnings are gone, thanks again for the quick reply, keep on the good work!

**Comment by daniel-mohemian** [comment]
Nice, good to hear that it works now! 🎉
