### ISSUE TITLE
Support for SD-JWT?

### ISSUE THREAD

**Issue by advatar** [airsidemobile/JOSESwift#297]
Any plans to support this? https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/

**Comment by daniel-moh** [comment]
Hi @advatar, no plans on our end at the moment. Once the draft matures into a standard we'd be open to discuss reviewing a PR adding this if. Note though that we don't support the JWT standard currently since we're focussed on the underlying JWS/JWE structures. If you think it would still make sense to add this to this library, please feel free to open another issue or a PR with a proposal of getting this in. 🙏
