### ISSUE TITLE
Cocoapods installation is failling

### ISSUE THREAD

**Issue by dj-neza** [airsidemobile/JOSESwift#78]
Hi!
When I try to add this pod to my Podfile I get this on "pod install":

<img width="366" alt="screen shot 2018-04-12 at 14 24 45" src="https://user-images.githubusercontent.com/15552533/38677063-67388546-3e5d-11e8-8c2e-44e9fff86dbe.png">

I have platform and source specified as in the Readme, other pods work normally. Any advice on how to solve it?

**Comment by daniel-mohemian** [comment]
Hi! Can you please run `pod repo update` and then run `pod install` again? Since we just recently released JOSESwift, you might not have it in your local specs repo.

In case that doesn't work, you can also directly pull from GitHub by including the pod like this in your Podfile: `pod 'JOSESwift', :git => 'https://github.com/airsidemobile/JOSESwift.git'`

**Comment by dj-neza** [comment]
Awesome it worked for me! 👍
