### ISSUE TITLE
Add RSA-OAEP and A128CBC-HS256 algorithms

### ISSUE THREAD

**Issue by drewpitchford** [airsidemobile/JOSESwift#82]
Can support for RSA-OAEP and A128CBC-HS256 algorithms be added?

**Comment by gigi-mohemian** [comment]
Hi @drewpitchford! We released `JOSESwift` a few of weeks ago, thus we don't support too many algorithms just yet. We plan to support more algorithms in upcoming versions, so stay tuned for that. However, RSA-OAEP and A128CBC-HS256 are not on our immediate roadmap.

In any case: we are always happy to receive contributions! Feel free to create a pull request in case you are motivated to add support for RSA-OAEP and A128CBC-HS256 yourself.

**Comment by daniel-mohemian** [comment]
@drewpitchford Hi again 👋 

Support for RSA-OAEP should actually be pretty easy to add since it seems it's already supported natively by the iOS Security framework's [`.rsaEncryptionOAEPSHA1`](https://developer.apple.com/documentation/security/seckeyalgorithm/1643711-rsaencryptionoaepsha1) algorithm (one would have to double check that this is actually the algorithm described in [RFC-7518 (JWA)](https://tools.ietf.org/html/rfc7518#section-4.3), though). 

We would just have to add the algorithm identifier and do some checks regarding input length.

The rough steps would be:

- Adding the respective [`AsymmetricKeyAlgorithm`](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/Algorithms.swift#L36) string identifier.
- Matching the algorithm identifier to [`.rsaEncryptionOAEPSHA1`](https://developer.apple.com/documentation/security/seckeyalgorithm/1643711-rsaencryptionoaepsha1) in the current crypto implementation file for RSA [here](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/CryptoImplementation/RSA.swift#L46).
- Performing some [input length](https://tools.ietf.org/html/rfc3447#section-7.1) checks for RSA OAEP [here](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/CryptoImplementation/RSA.swift#L56) and [here](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/CryptoImplementation/RSA.swift#L65).
- Test, test, test. 😉 

Feel free to have a look, it really shouldn't be too much work. Otherwise, I'll add it to our project backlog for future implementation. Can' promise an ETA at the moment, though. 🙂 

As for A128CBC-HS256, we would have to extend the [AES implementation](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/CryptoImplementation/AES.swift) file to utilize CommonCryptos AES implementation. Maybe a little more work than for RSA, but should be doable as well. 👍 

Let me know what you think.

**Comment by garrefa** [comment]
Is someone working in this feature? I need this for a project Im working on and I want to take care of it if nobody is already working on it.

**Comment by drewpitchford** [comment]
@garrefa I am not working on it. We are using a golang library for now. Until iOS mandates bitcode, that works for us.

**Comment by daniel-mohemian** [comment]
@garrefa Sounds great! 🎉 

We are not working on it at this time. So if you are motivated we'd be happy to merge a pull request implementing those algorithms. 🔒

**Comment by daniel-mohemian** [comment]
RSA-OAEP is now supported as of 1.7.0 thanks to @garrefa.

I'll close this issue and open another one just for A128CBC-HS256.
