### ISSUE TITLE
JWE: CompactDeserializable Error

### ISSUE THREAD

**Issue by emraz** [airsidemobile/JOSESwift#89]
Cannot invoke 'JWE.init' with an argument list of type '(header: JWEHeader, encryptedKey: Data, initializationVector: Data, ciphertext: Data, authenticationTag: Data)'

**Comment by daniel-mohemian** [comment]
Hi @emraz,

thanks for trying out JOSESwift! 🎉

You get this error because you're calling a [private initializer](https://github.com/airsidemobile/JOSESwift/blob/master/JOSESwift/Sources/JWE.swift#L126). That initializer indeed exists but it is only used internally to initialize a JWE after deserializing it. We currently only support deserializing of JWEs in [compact serialization](https://tools.ietf.org/html/rfc7516#section-3.1). If you need support for deserializing JWEs in [JSON serialization](https://tools.ietf.org/html/rfc7516#section-3.2), we'd gladly merge a pull request from you. 

As a _temporary_ workaround, you could add your own initializer that directly accepts the respective JWE parts:

``` swift
extension JWE {
    init(header: JWEHeader, encryptedKey: Data, initializationVector: Data, ciphertext: Data, authenticationTag: Data) {
        self.header = header
        self.encryptedKey = encryptedKey
        self.initializationVector = initializationVector
        self.ciphertext = ciphertext
        self.authenticationTag = authenticationTag
    }
}
```

:warning: Keep in mind, that adding such an initializer to a struct outside of its module will produce a warning in Swift 4 and an error in Swift 5. You can read more about that [here](https://github.com/apple/swift-evolution/blob/master/proposals/0189-restrict-cross-module-struct-initializers.md).

You can read more about how to initialize a JWE with existing compact serialized data in [the wiki](https://github.com/airsidemobile/JOSESwift/wiki/jwe#decrypting-an-existing-serialization).

I think that should clarify why you're experiencing this issue. Let me know if you need any further assistance.
